import { NextResponse,type NextRequest } from "next/server";
import { getAdminSession } from "@/lib/admin-auth";
import { hotelScope,writeAuditLog } from "@/lib/hotel-ops";
import { supabaseRequest } from "@/lib/supabase-rest";

export async function GET(request:NextRequest){const s=getAdminSession(request);if(!s)return NextResponse.json({error:"Unauthorized"},{status:401});const h=hotelScope(s,request.nextUrl.searchParams.get("hotelId"));if(!h)return NextResponse.json({error:"Hotel required"},{status:400});const [rr,cr,sr]=await Promise.all([supabaseRequest(`?select=id,room_no,room_type,status&hotel_id=eq.${h}&is_active=eq.true&order=room_no.asc`,{},"hotel_rooms"),supabaseRequest(`?select=*&hotel_id=eq.${h}&order=created_at.desc&limit=100`,{},"hotel_housekeeping_checks"),supabaseRequest(`?select=id,name&hotel_id=eq.${h}&is_active=eq.true&staff_type=eq.cleaning&order=name.asc`,{},"hotel_staff_members")]);if(!rr.ok||!cr.ok||!sr.ok)return NextResponse.json({error:"Unable to load housekeeping."},{status:500});return NextResponse.json({rooms:await rr.json(),checks:await cr.json(),staff:await sr.json()});}

export async function POST(request:NextRequest){const s=getAdminSession(request);if(!s)return NextResponse.json({error:"Unauthorized"},{status:401});if(s.role!=="hotel_admin"||!s.hotelId)return NextResponse.json({error:"Hotel login required."},{status:403});const b=await request.json().catch(()=>({})) as {roomId?:string;staffId?:string;status?:string;notes?:string};if(!b.roomId||!["pending","cleaning","ready","issue"].includes(b.status||""))return NextResponse.json({error:"Room and valid status required."},{status:400});const roomRes=await supabaseRequest(`?select=id,room_no,status&id=eq.${b.roomId}&hotel_id=eq.${s.hotelId}&limit=1`,{},"hotel_rooms");if(!roomRes.ok)return NextResponse.json({error:"Unable to verify room."},{status:500});const room=(await roomRes.json() as Array<{id:string;room_no:string;status:string}>)[0];if(!room)return NextResponse.json({error:"Room not found."},{status:404});let cleanedByName:string|null=null;if(b.staffId){const staffRes=await supabaseRequest(`?select=id,name&id=eq.${b.staffId}&hotel_id=eq.${s.hotelId}&limit=1`,{},"hotel_staff_members");if(staffRes.ok)cleanedByName=((await staffRes.json()) as Array<{name:string}>)[0]?.name??null;}
const openRes=await supabaseRequest(`?select=id,status&room_id=eq.${room.id}&status=in.(pending,cleaning,issue)&order=created_at.desc&limit=1`,{},"hotel_housekeeping_checks");const open=openRes.ok?((await openRes.json()) as Array<{id:string;status:string}>)[0]:null;const now=new Date().toISOString();let checkId=open?.id??null;if(open){const update:any={status:b.status,notes:b.notes?.trim()||null,cleaned_by_staff_id:b.staffId||null,cleaned_by_name:cleanedByName,updated_at:now};if(b.status==="cleaning")update.started_at=now;if(b.status==="ready")update.completed_at=now;const r=await supabaseRequest(`?id=eq.${open.id}`,{method:"PATCH",headers:{Prefer:"return=minimal"},body:JSON.stringify(update)},"hotel_housekeeping_checks");if(!r.ok)return NextResponse.json({error:"Unable to update housekeeping."},{status:500});}else{const payload:any={hotel_id:s.hotelId,room_id:room.id,room_no:room.room_no,status:b.status,cleaned_by_staff_id:b.staffId||null,cleaned_by_name:cleanedByName,notes:b.notes?.trim()||null,recorded_by:s.username};if(b.status==="cleaning")payload.started_at=now;if(b.status==="ready")payload.completed_at=now;const r=await supabaseRequest("",{method:"POST",headers:{Prefer:"return=representation"},body:JSON.stringify(payload)},"hotel_housekeeping_checks");if(!r.ok)return NextResponse.json({error:"Unable to record housekeeping."},{status:500});checkId=((await r.json()) as Array<{id:string}>)[0]?.id??null;}
if(b.status==="ready"){await supabaseRequest(`?id=eq.${room.id}`,{method:"PATCH",headers:{Prefer:"return=minimal"},body:JSON.stringify({status:"available",updated_by:s.username,updated_at:now})},"hotel_rooms");}else if(b.status==="issue"){await supabaseRequest(`?id=eq.${room.id}`,{method:"PATCH",headers:{Prefer:"return=minimal"},body:JSON.stringify({status:"maintenance",updated_by:s.username,updated_at:now})},"hotel_rooms");}else if(room.status==="available"&&b.status!=="ready"){await supabaseRequest(`?id=eq.${room.id}`,{method:"PATCH",headers:{Prefer:"return=minimal"},body:JSON.stringify({status:"dirty",updated_by:s.username,updated_at:now})},"hotel_rooms");}
await writeAuditLog(s,`housekeeping_${b.status}`,"housekeeping_check",checkId,s.hotelId,{roomNo:room.room_no,staff:cleanedByName});return NextResponse.json({success:true});}
