import type { Metadata } from "next";
import Link from "next/link";
import { Mail, MapPin, MessageCircle, Phone } from "lucide-react";
import SmartImage from "@/components/SmartImage";
import { hotels } from "@/data/hotels";

export const metadata: Metadata = { title: "Contact Supraja Hotels | Hyderabad", description: "Contact Hotel Supraja Cyber View, Hotel Supraja Residency or Hotel Supraja Lodge by phone or WhatsApp to check rooms, rates and booking details.", alternates: { canonical: "/contact" }, openGraph: { title: "Contact Supraja Hotels", description: "Call or WhatsApp your preferred Supraja Hotel in Hyderabad.", url: "/contact", siteName: "Supraja Hotels", images: [{ url: "/images/social/supraja-hotels-og.jpg", width: 1200, height: 630, alt: "Contact Supraja Hotels" }], locale: "en_IN", type: "website" } };

export default function ContactPage(){return <main className="bg-white pb-20 text-slate-900 md:pb-0">
 <section className="relative isolate overflow-hidden bg-slate-950 text-white"><SmartImage src={hotels[0].images.hero} alt="Contact Supraja Hotels Hyderabad" fill isHero className="object-cover opacity-55" sizes="100vw"/><div className="absolute inset-0 bg-gradient-to-r from-slate-950/95 via-slate-950/70 to-slate-950/25"/><div className="container-custom relative z-10 px-5 py-20 lg:py-24"><div className="max-w-4xl"><p className="text-sm font-bold uppercase tracking-[0.24em] text-amber-300">Contact Supraja Hotels</p><h1 className="mt-4 text-4xl font-bold leading-[1.05] tracking-tight md:text-6xl">Contact Your Preferred Supraja Hotel</h1><p className="mt-6 max-w-3xl text-lg leading-8 text-slate-300">Choose your hotel and call or WhatsApp the team to check available rooms, today’s rates, directions and booking details.</p></div></div></section>
 <section className="bg-[#f7f5f1] px-4 py-16 lg:py-24"><div className="container-custom"><div className="max-w-5xl"><p className="text-sm font-bold uppercase tracking-[0.22em] text-amber-700">Hotel Contacts</p><h2 className="mt-3 text-3xl font-bold tracking-tight md:text-5xl">Call or WhatsApp the Hotel Directly</h2></div><div className="mt-10 grid gap-7 lg:grid-cols-3">{hotels.map(h=><article key={h.slug} className="overflow-hidden rounded-[1.75rem] bg-white shadow-[0_18px_50px_rgba(15,23,42,.08)]"><div className="relative h-64"><SmartImage src={h.images.hero} alt={h.seo.featuredImageAlt} fill className="object-cover" sizes="(max-width:1024px) 100vw,33vw"/><div className="absolute inset-0 bg-gradient-to-t from-black/65 to-transparent"/><div className="absolute inset-x-0 bottom-0 p-5 text-white"><p className="flex items-center gap-2 text-sm"><MapPin size={15}/>{h.location}</p><h3 className="mt-2 text-2xl font-bold">{h.name}</h3></div></div><div className="p-6"><div className="space-y-3 text-sm"><p className="flex items-start gap-3"><Phone size={17} className="mt-0.5 text-blue-700"/><a href={`tel:+91${h.phone}`} className="font-bold text-slate-900">{h.phone}</a></p><p className="flex items-start gap-3"><Mail size={17} className="mt-0.5 text-blue-700"/><span className="break-all text-slate-600">{h.email}</span></p><p className="flex items-start gap-3"><MapPin size={17} className="mt-0.5 text-blue-700"/><span className="leading-6 text-slate-600">{h.address}</span></p></div><div className="mt-6 grid grid-cols-2 gap-2"><a href={`tel:+91${h.phone}`} className="inline-flex min-h-11 items-center justify-center gap-2 rounded-full border border-slate-300 text-sm font-bold"><Phone size={16}/>Call</a><a href={`https://wa.me/91${h.whatsapp}?text=Hi%20I%20would%20like%20to%20check%20room%20availability%20at%20${encodeURIComponent(h.name)}`} target="_blank" rel="noopener noreferrer" className="inline-flex min-h-11 items-center justify-center gap-2 rounded-full bg-green-600 text-sm font-bold text-white"><MessageCircle size={16}/>WhatsApp</a></div><Link href={`/hotels/${h.slug}`} className="mt-4 inline-block text-sm font-bold text-blue-800 hover:underline">View rooms & hotel details</Link></div></article>)}</div></div></section>
 <section className="bg-white px-4 py-16 lg:py-20"><div className="container-custom grid gap-8 lg:grid-cols-[1fr_.8fr]"><div><p className="text-sm font-bold uppercase tracking-[0.22em] text-amber-700">Before You Arrive</p><h2 className="mt-3 text-3xl font-bold tracking-tight md:text-4xl">Helpful Details to Confirm</h2><div className="mt-6 grid gap-3 sm:grid-cols-2">{["Available room types","Today’s room rate","Check-in and ID requirements","Parking and vehicle access","Directions to the hotel","Special stay requests"].map(x=><div key={x} className="rounded-2xl bg-[#f7f5f1] p-4 font-semibold text-slate-700">{x}</div>)}</div></div><div className="rounded-[1.75rem] bg-slate-950 p-7 text-white"><p className="text-sm font-bold uppercase tracking-[0.2em] text-amber-300">Not Sure Which Hotel?</p><h3 className="mt-3 text-2xl font-bold">Tell Us Where You Are Visiting</h3><p className="mt-4 leading-7 text-slate-300">Share your destination in Madhapur, HITEC City, Chandanagar, Lingampally, BHEL or Miyapur and we will help you choose the nearest Supraja Hotel.</p><a href="https://wa.me/919550776161?text=Hi%20I%20need%20help%20choosing%20a%20Supraja%20Hotel" target="_blank" rel="noopener noreferrer" className="mt-6 inline-flex min-h-12 items-center gap-2 rounded-full bg-green-600 px-6 text-sm font-bold"><MessageCircle size={17}/>Ask on WhatsApp</a></div></div></section>
 <div className="fixed inset-x-0 bottom-0 z-50 grid grid-cols-2 border-t border-slate-200 bg-white p-2 shadow-[0_-8px_30px_rgba(15,23,42,.14)] md:hidden"><a href="tel:+919550776161" className="inline-flex min-h-12 items-center justify-center gap-2 text-sm font-bold"><Phone size={18}/>Call</a><a href="https://wa.me/919550776161" target="_blank" rel="noopener noreferrer" className="inline-flex min-h-12 items-center justify-center gap-2 rounded-full bg-green-600 text-sm font-bold text-white"><MessageCircle size={18}/>WhatsApp</a></div>
 </main>}
