import { NextResponse,type NextRequest } from "next/server";
import { getAdminSession } from "@/lib/admin-auth";
import { hotelScope,writeAuditLog } from "@/lib/hotel-ops";
import { supabaseRequest } from "@/lib/supabase-rest";

export async function GET(request:NextRequest){const s=getAdminSession(request);if(!s)return NextResponse.json({error:"Unauthorized"},{status:401});const h=hotelScope(s,request.nextUrl.searchParams.get("hotelId"));if(!h)return NextResponse.json({error:"Hotel required"},{status:400});const r=await supabaseRequest(`?select=*&hotel_id=eq.${h}&order=created_at.desc&limit=50`,{},"hotel_shift_handovers");if(!r.ok)return NextResponse.json({error:"Unable to load handovers."},{status:500});return NextResponse.json({handovers:await r.json()});}

export async function POST(request:NextRequest){const s=getAdminSession(request);if(!s)return NextResponse.json({error:"Unauthorized"},{status:401});if(s.role!=="hotel_admin"||!s.hotelId)return NextResponse.json({error:"Hotel login required."},{status:403});const b=await request.json().catch(()=>({})) as {incomingName?:string;cashHandover?:number;occupiedRooms?:number;pendingArrivals?:number;pendingPayments?:number;openComplaints?:number;openMaintenance?:number;masterKeyStatus?:string;notes?:string};const payload={hotel_id:s.hotelId,outgoing_username:s.username,outgoing_name:s.displayName,incoming_name:b.incomingName?.trim()||null,cash_handover:Number(b.cashHandover||0),occupied_rooms:Math.max(0,Math.floor(Number(b.occupiedRooms||0))),pending_arrivals:Math.max(0,Math.floor(Number(b.pendingArrivals||0))),pending_payments:Number(b.pendingPayments||0),open_complaints:Math.max(0,Math.floor(Number(b.openComplaints||0))),open_maintenance:Math.max(0,Math.floor(Number(b.openMaintenance||0))),master_key_status:b.masterKeyStatus?.trim()||null,notes:b.notes?.trim()||null,status:"submitted"};const r=await supabaseRequest("",{method:"POST",headers:{Prefer:"return=representation"},body:JSON.stringify(payload)},"hotel_shift_handovers");if(!r.ok)return NextResponse.json({error:"Unable to submit handover."},{status:500});const row=(await r.json() as Array<{id:string}>)[0];await writeAuditLog(s,"handover_submitted","shift_handover",row?.id??null,s.hotelId,{cashHandover:payload.cash_handover,occupiedRooms:payload.occupied_rooms});return NextResponse.json({success:true,id:row?.id});}

export async function PATCH(request:NextRequest){const s=getAdminSession(request);if(!s)return NextResponse.json({error:"Unauthorized"},{status:401});if(s.role!=="hotel_admin"||!s.hotelId)return NextResponse.json({error:"Hotel login required."},{status:403});const b=await request.json().catch(()=>({})) as {id?:string};if(!b.id)return NextResponse.json({error:"Handover required."},{status:400});const r=await supabaseRequest(`?id=eq.${b.id}&hotel_id=eq.${s.hotelId}&status=eq.submitted`,{method:"PATCH",headers:{Prefer:"return=representation"},body:JSON.stringify({status:"accepted",accepted_by:s.username,accepted_at:new Date().toISOString(),incoming_username:s.username,incoming_name:s.displayName})},"hotel_shift_handovers");if(!r.ok)return NextResponse.json({error:"Unable to accept handover."},{status:500});const rows=await r.json() as Array<{id:string}>;if(!rows.length)return NextResponse.json({error:"Handover already accepted or not found."},{status:404});await writeAuditLog(s,"handover_accepted","shift_handover",b.id,s.hotelId,{});return NextResponse.json({success:true});}
