"use client";

import {FormEvent,useCallback,useEffect,useMemo,useState} from "react";
import Link from "next/link";
import {Building2,Clock3,LogOut,Play,RefreshCw,UserPlus,Users} from "lucide-react";

type Session={username:string;displayName:string;role:"master"|"hotel_admin";hotelId:string|null;hotelName:string|null};
type Hotel={id:string;name:string;code?:string};
type Shift={id:string;hotel_id:string;admin_username:string;display_name:string;employee_id?:string|null;started_at:string;ended_at:string|null;status:string;handover_note:string|null};
type Employee={id:string;name:string;designation:string;is_active:boolean};
type Staff={id:string;hotel_id:string;name:string;staff_type:string;phone:string|null};
type Attendance={id:string;staff_member_id:string;attendance_date:string;status:string;recorded_by:string;marked_at?:string|null;recorded_by_employee_name?:string|null;hotel_staff_members?:{name?:string;staff_type?:string}|null};
type ChecklistEntry={checklist_type:string;is_completed:boolean;item_key:string};
const card="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm",input="w-full rounded-xl border border-slate-300 bg-white px-3 py-2.5 text-sm text-slate-900 outline-none focus:border-blue-700 focus:ring-2 focus:ring-blue-100",btn="inline-flex items-center justify-center gap-2 rounded-xl px-4 py-2.5 text-sm font-semibold transition disabled:cursor-not-allowed disabled:opacity-50";

export default function OperationsPage(){
 const[session,setSession]=useState<Session|null>(null),[hotels,setHotels]=useState<Hotel[]>([]),[selectedHotel,setSelectedHotel]=useState(""),[shifts,setShifts]=useState<Shift[]>([]),[employees,setEmployees]=useState<Employee[]>([]),[staff,setStaff]=useState<Staff[]>([]),[attendance,setAttendance]=useState<Attendance[]>([]),[checklistEntries,setChecklistEntries]=useState<ChecklistEntry[]>([]),[busy,setBusy]=useState(false),[message,setMessage]=useState(""),[newStaff,setNewStaff]=useState({name:"",phone:""}),[shiftNote,setShiftNote]=useState(""),[shiftIdentity,setShiftIdentity]=useState({employeeId:"",pin:""}),[correction,setCorrection]=useState<{staffMemberId:string;status:string;reason:string}|null>(null);
 const activeShift=useMemo(()=>session?.role==="hotel_admin"?shifts.find(s=>s.status==="active"&&s.admin_username===session.username):shifts.find(s=>s.status==="active"),[shifts,session]);
 const startDone=checklistEntries.filter(e=>e.checklist_type==="shift_start"&&e.is_completed).length;
 const endDone=checklistEntries.filter(e=>e.checklist_type==="shift_end"&&e.is_completed).length;
 const startComplete=startDone>=6,endComplete=endDone>=8;
 const load=useCallback(async()=>{setMessage("");const sr=await fetch("/api/admin/session",{cache:"no-store"});if(sr.status===401){location.href="/admin/login";return}const sd=await sr.json() as {session:Session};setSession(sd.session);const[hr,er]=await Promise.all([fetch("/api/admin/hotels",{cache:"no-store"}),fetch("/api/admin/employees",{cache:"no-store"})]);const hd=await hr.json() as {hotels?:Hotel[]},ed=await er.json() as {employees?:Employee[]};const hs=hd.hotels??[],es=(ed.employees??[]).filter(e=>e.is_active);setHotels(hs);setEmployees(es);setShiftIdentity(v=>({...v,employeeId:v.employeeId||es[0]?.id||""}));const id=sd.session.role==="hotel_admin"?sd.session.hotelId??"":selectedHotel||hs[0]?.id||"";if(!selectedHotel&&id)setSelectedHotel(id);const q=id?`?hotelId=${encodeURIComponent(id)}`:"";const[a,b,c,d]=await Promise.all([fetch(`/api/admin/shifts${q}`,{cache:"no-store"}),fetch(`/api/admin/staff${q}`,{cache:"no-store"}),fetch(`/api/admin/staff-attendance${q}`,{cache:"no-store"}),fetch(`/api/admin/checklists${q}`,{cache:"no-store"})]);const ad=await a.json(),bd=await b.json(),cd=await c.json(),dd=await d.json();setShifts(ad.shifts??[]);setStaff(bd.staff??[]);setAttendance(cd.attendance??[]);setChecklistEntries(dd.entries??[]);},[selectedHotel]);
 useEffect(()=>{void load()},[load]);
 async function shiftAction(action:"start"|"end"){
   if(action==="end"&&!endComplete){const ok=window.confirm(`Shift End checklist is incomplete (${endDone}/8). End the shift anyway? This will be recorded in the audit history.`);if(!ok)return;}
   setBusy(true);setMessage("");const payload=action==="start"?{action,note:shiftNote,employeeId:shiftIdentity.employeeId,pin:shiftIdentity.pin}:{action,note:shiftNote};const r=await fetch("/api/admin/shifts",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)}),d=await r.json();setMessage(r.ok?(action==="start"?"Shift started. Complete the Shift Start checklist before recording attendance.":d.checklistIncomplete?`Shift ended. Shift End checklist was incomplete (${d.shiftEndChecklistCompleted}/8) and has been recorded for audit.`:"Shift ended successfully."):d.error??"Unable to update shift.");if(r.ok){setShiftNote("");setShiftIdentity(v=>({...v,pin:""}))}await load();setBusy(false)}
 async function addStaff(e:FormEvent){e.preventDefault();setBusy(true);const r=await fetch("/api/admin/staff",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...newStaff,hotelId:selectedHotel,staffType:"cleaning"})}),d=await r.json();setMessage(r.ok?"Cleaning staff member added.":d.error??"Unable to add staff.");if(r.ok)setNewStaff({name:"",phone:""});await load();setBusy(false)}
 async function markAttendance(staffMemberId:string,status:string,correctionMode=false,reason=""){setBusy(true);const r=await fetch("/api/admin/staff-attendance",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({staffMemberId,hotelId:selectedHotel,status,correction:correctionMode,correctionReason:reason})}),d=await r.json();setMessage(r.ok?(correctionMode?"Attendance corrected and original entry preserved in audit history.":"Attendance recorded with timestamp."):d.error??"Unable to save attendance.");if(r.ok)setCorrection(null);await load();setBusy(false)}
 async function logout(){await fetch("/api/admin-logout",{method:"POST"});location.href="/admin/login"}
 if(!session)return <main className="min-h-screen bg-slate-50 p-8 text-slate-600">Loading hotel operations...</main>;
 return <main className="min-h-screen bg-slate-50 text-slate-950"><header className="border-b bg-white"><div className="mx-auto flex max-w-7xl flex-col gap-4 px-4 py-5 sm:px-6 lg:flex-row lg:items-center lg:justify-between"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-amber-600">Supraja Hotels</p><h1 className="mt-1 text-2xl font-bold">Operations Control</h1><p className="mt-1 text-sm text-slate-600">Shift identity, staff attendance and operational accountability.</p></div><div className="flex flex-wrap items-center gap-2"><div className="rounded-xl bg-slate-100 px-3 py-2 text-sm font-semibold">{session.role==="master"?"Master Admin":session.hotelName}</div><Link href="/admin/home" className={`${btn} border bg-white`}>Home</Link><Link href="/admin/checklists" className={`${btn} border border-blue-200 bg-blue-50 text-blue-900`}>Checklists</Link><button onClick={()=>void load()} className={`${btn} border bg-white`}><RefreshCw size={16}/>Refresh</button><button onClick={()=>void logout()} className={`${btn} bg-slate-900 text-white`}><LogOut size={16}/>Logout</button></div></div></header><div className="mx-auto max-w-7xl space-y-5 px-4 py-6 sm:px-6">{session.role==="master"&&<section className={card}><select className={input} value={selectedHotel} onChange={e=>setSelectedHotel(e.target.value)}>{hotels.map(h=><option key={h.id} value={h.id}>{h.name}</option>)}</select></section>}{message&&<div className="rounded-xl border border-blue-200 bg-blue-50 px-4 py-3 text-sm font-medium text-blue-900">{message}</div>}
 <section className="grid gap-4 md:grid-cols-3"><div className={card}><Clock3 className="text-blue-800"/><p className="mt-2 text-sm text-slate-500">Current shift</p><p className="font-bold">{activeShift?activeShift.display_name:"No active shift"}</p>{activeShift&&<p className="mt-2 text-xs text-slate-500">Started {new Date(activeShift.started_at).toLocaleString()}</p>}</div><div className={card}><Users className="text-blue-800"/><p className="mt-2 text-sm text-slate-500">Cleaning staff</p><p className="text-2xl font-bold">{staff.length}</p></div><div className={card}><Building2 className="text-blue-800"/><p className="mt-2 text-sm text-slate-500">Today marked</p><p className="text-2xl font-bold">{attendance.length}</p></div></section>
 {session.role==="hotel_admin"&&<section className={card}><h2 className="text-lg font-bold">Shift</h2>{!activeShift?<><p className="mt-1 text-sm text-slate-600">Select your name and enter your personal PIN.</p><div className="mt-4 grid gap-3 sm:grid-cols-2"><select className={input} value={shiftIdentity.employeeId} onChange={e=>setShiftIdentity(v=>({...v,employeeId:e.target.value}))}><option value="">Select employee</option>{employees.map(e=><option key={e.id} value={e.id}>{e.name} · {e.designation}</option>)}</select><input className={input} type="password" inputMode="numeric" pattern="[0-9]{4,6}" placeholder="Employee PIN" value={shiftIdentity.pin} onChange={e=>setShiftIdentity(v=>({...v,pin:e.target.value.replace(/\D/g,"").slice(0,6)}))}/></div></>:<><p className="mt-1 text-sm text-slate-600"><b>{activeShift.display_name}</b> is currently on duty.</p><div className="mt-3 rounded-xl border border-slate-200 bg-slate-50 p-3 text-sm"><div>Shift Start checklist: <b>{startDone}/6</b> {startComplete?"✓":""}</div><div className="mt-1">Shift End checklist: <b>{endDone}/8</b> {endComplete?"✓":""}</div>{!startComplete&&<p className="mt-2 text-amber-800">Complete Shift Start checklist before staff attendance.</p>}{!endComplete&&<p className="mt-1 text-slate-600">Shift End checklist is recommended before ending the shift. You can still end the shift if needed; incomplete items will be recorded in audit history.</p>}</div></>}<textarea className={`${input} mt-4 min-h-20`} placeholder="Optional shift / handover note" value={shiftNote} onChange={e=>setShiftNote(e.target.value)}/><div className="mt-3 flex gap-2">{!activeShift?<button disabled={busy||!shiftIdentity.employeeId||!shiftIdentity.pin} onClick={()=>void shiftAction("start")} className={`${btn} bg-blue-800 text-white`}><Play size={16}/>Start Shift</button>:<button disabled={busy} onClick={()=>void shiftAction("end")} className={`${btn} bg-slate-900 text-white`}><Clock3 size={16}/>End Shift</button>}</div></section>}
 <section className={card}><h2 className="text-lg font-bold">Cleaning staff attendance</h2><p className="mt-1 text-sm text-slate-600">First attendance entry is locked. Corrections require a reason and preserve the original entry in audit history.</p><div className="mt-4 overflow-x-auto"><table className="w-full min-w-[760px] text-left text-sm"><thead><tr className="border-b text-slate-500"><th className="py-3 pr-4">Staff</th><th className="py-3 pr-4">Type</th><th className="py-3 pr-4">Today</th><th className="py-3 pr-4">Recorded</th><th className="py-3">Action</th></tr></thead><tbody>{staff.map(m=>{const a=attendance.find(x=>x.staff_member_id===m.id);return <tr key={m.id} className="border-b"><td className="py-3 pr-4 font-semibold">{m.name}</td><td className="py-3 pr-4 capitalize text-slate-600">{m.staff_type}</td><td className="py-3 pr-4 capitalize">{a?.status?.replace("_"," ")??"Not marked"}</td><td className="py-3 pr-4 text-xs text-slate-600">{a?.marked_at?<>{new Date(a.marked_at).toLocaleString()}<br/>by {a.recorded_by_employee_name||"On-duty employee"}</>:"—"}</td><td className="py-3">{!a?<div className="flex flex-wrap gap-1.5">{["present","absent","leave","half_day"].map(s=><button disabled={busy||!activeShift||!startComplete} key={s} onClick={()=>void markAttendance(m.id,s)} className="rounded-lg border px-2.5 py-1.5 text-xs font-semibold capitalize">{s.replace("_"," ")}</button>)}</div>:<button disabled={busy||!activeShift} onClick={()=>setCorrection({staffMemberId:m.id,status:a.status,reason:""})} className="rounded-lg border px-3 py-1.5 text-xs font-semibold">Correct Attendance</button>}</td></tr>})}</tbody></table></div></section>
 {correction&&<section className="rounded-2xl border border-amber-200 bg-amber-50 p-5"><h2 className="font-bold">Correct attendance</h2><p className="mt-1 text-sm text-amber-900">Choose the corrected status and enter a mandatory reason.</p><div className="mt-3 grid gap-3 sm:grid-cols-3"><select className={input} value={correction.status} onChange={e=>setCorrection(v=>v?{...v,status:e.target.value}:v)}>{["present","absent","leave","half_day"].map(s=><option key={s} value={s}>{s.replace("_"," ")}</option>)}</select><input className={input} placeholder="Correction reason" value={correction.reason} onChange={e=>setCorrection(v=>v?{...v,reason:e.target.value}:v)}/><div className="flex gap-2"><button disabled={busy||correction.reason.trim().length<3} onClick={()=>void markAttendance(correction.staffMemberId,correction.status,true,correction.reason)} className={`${btn} bg-amber-700 text-white`}>Save Correction</button><button onClick={()=>setCorrection(null)} className={`${btn} border bg-white`}>Cancel</button></div></div></section>}
 <section className={card}><h2 className="text-lg font-bold">Add cleaning staff</h2><form onSubmit={addStaff} className="mt-4 grid gap-3 sm:grid-cols-[1fr_1fr_auto]"><input className={input} placeholder="Staff name" value={newStaff.name} onChange={e=>setNewStaff(v=>({...v,name:e.target.value}))} required/><input className={input} placeholder="Phone (optional)" value={newStaff.phone} onChange={e=>setNewStaff(v=>({...v,phone:e.target.value}))}/><button disabled={busy||!selectedHotel} className={`${btn} bg-blue-800 text-white`}><UserPlus size={16}/>Add Staff</button></form></section>
 <section className={card}><h2 className="text-lg font-bold">Recent shift history</h2><div className="mt-4 space-y-2">{shifts.slice(0,8).map(s=><div key={s.id} className="flex justify-between rounded-xl bg-slate-50 px-4 py-3 text-sm"><div><b>{s.display_name}</b><span className="ml-2 text-slate-500">{new Date(s.started_at).toLocaleString()}</span></div><span className="rounded-full bg-slate-200 px-2 py-1 text-xs font-bold">{s.status}</span></div>)}</div></section></div></main>
}
