import { NextResponse,type NextRequest } from "next/server";
import { getAdminSession } from "@/lib/admin-auth";
import { hotelScope,writeAuditLog } from "@/lib/hotel-ops";
import { supabaseRequest } from "@/lib/supabase-rest";

function indiaDate(){return new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Kolkata",year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date());}
export async function GET(request:NextRequest){const s=getAdminSession(request);if(!s)return NextResponse.json({error:"Unauthorized"},{status:401});const h=hotelScope(s,request.nextUrl.searchParams.get("hotelId"));if(!h)return NextResponse.json({error:"Hotel required"},{status:400});const d=request.nextUrl.searchParams.get("date")||indiaDate();const r=await supabaseRequest(`?select=*&hotel_id=eq.${encodeURIComponent(h)}&reconciliation_date=eq.${d}&limit=1`,{},"hotel_daily_reconciliations");if(!r.ok)return NextResponse.json({error:"Unable to load reconciliation."},{status:500});return NextResponse.json({reconciliation:(await r.json())[0]??null});}
export async function POST(request:NextRequest){const s=getAdminSession(request);if(!s)return NextResponse.json({error:"Unauthorized"},{status:401});if(s.role!=="hotel_admin"||!s.hotelId)return NextResponse.json({error:"Hotel login required."},{status:403});const b=await request.json().catch(()=>({})) as {openingCash?:number;approvedPayouts?:number;actualClosingCash?:number;notes?:string};const date=indiaDate();const pr=await supabaseRequest(`?select=amount,payment_type,payment_mode&hotel_id=eq.${s.hotelId}&created_at=gte.${date}T00:00:00%2B05:30&created_at=lt.${date}T23:59:59%2B05:30`,{},"hotel_payments");if(!pr.ok)return NextResponse.json({error:"Unable to calculate collections."},{status:500});const ps=await pr.json() as {amount:number;payment_type:string;payment_mode:string}[];const total=(mode:string)=>ps.filter(p=>p.payment_mode===mode).reduce((a,p)=>a+(p.payment_type==="refund"?-Number(p.amount):Number(p.amount)),0);const cash=total("cash"),opening=Number(b.openingCash||0),payout=Number(b.approvedPayouts||0),actual=Number(b.actualClosingCash||0),expected=opening+cash-payout,variance=actual-expected;const payload={hotel_id:s.hotelId,reconciliation_date:date,opening_cash:opening,approved_payouts:payout,actual_closing_cash:actual,expected_cash:expected,cash_variance:variance,upi_total:total("upi"),card_total:total("card"),bank_transfer_total:total("bank_transfer"),notes:b.notes?.trim()||null,recorded_by:s.username,status:Math.abs(variance)>0.01?"variance_pending":"submitted",updated_at:new Date().toISOString()};const r=await supabaseRequest("?on_conflict=hotel_id,reconciliation_date",{method:"POST",headers:{Prefer:"resolution=merge-duplicates,return=representation"},body:JSON.stringify(payload)},"hotel_daily_reconciliations");if(!r.ok)return NextResponse.json({error:"Unable to save reconciliation."},{status:500});const row=(await r.json())[0];await writeAuditLog(s,"reconciliation_submitted","daily_reconciliation",row?.id??null,s.hotelId,{expectedCash:expected,actualClosingCash:actual,variance});return NextResponse.json({success:true,reconciliation:row});}
export async function PATCH(request:NextRequest){const s=getAdminSession(request);if(!s)return NextResponse.json({error:"Unauthorized"},{status:401});if(s.role!=="master")return NextResponse.json({error:"Master Admin required."},{status:403});const b=await request.json().catch(()=>({})) as {id?:string;action?:string};if(!b.id||b.action!=="verify")return NextResponse.json({error:"Invalid request."},{status:400});const r=await supabaseRequest(`?id=eq.${encodeURIComponent(b.id)}`,{method:"PATCH",headers:{Prefer:"return=representation"},body:JSON.stringify({status:"verified",verified_by:s.username,verified_at:new Date().toISOString(),updated_at:new Date().toISOString()})},"hotel_daily_reconciliations");if(!r.ok)return NextResponse.json({error:"Unable to verify."},{status:500});const row=(await r.json())[0];await writeAuditLog(s,"reconciliation_verified","daily_reconciliation",b.id,row?.hotel_id??null,{});return NextResponse.json({success:true});}
