create table if not exists public.hotel_leads (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  name text not null,
  phone text not null,
  email text,
  property text not null,
  enquiry_type text not null default 'Room booking',
  check_in date,
  check_out date,
  guests integer check (guests is null or guests between 1 and 50),
  message text,
  status text not null default 'new' check (status in ('new','contacted','qualified','booked','closed')),
  notes text,
  source_page text,
  referrer text,
  utm_source text,
  utm_medium text,
  utm_campaign text
);

create index if not exists hotel_leads_created_at_idx on public.hotel_leads (created_at desc);
create index if not exists hotel_leads_status_created_at_idx on public.hotel_leads (status, created_at desc);
create index if not exists hotel_leads_property_created_at_idx on public.hotel_leads (property, created_at desc);
alter table public.hotel_leads enable row level security;
revoke all on table public.hotel_leads from anon, authenticated;
comment on table public.hotel_leads is 'Server-only enquiries submitted through suprajahotels.com.';
