create table if not exists public.hotel_click_events (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  event_type text not null check (
    event_type in (
      'page_view',
      'call_click',
      'whatsapp_click',
      'email_click',
      'booking_click',
      'navigation_click'
    )
  ),
  page_path text not null,
  page_title text,
  target_url text,
  target_label text,
  visitor_id text not null,
  session_id text not null,
  referrer text,
  device_type text not null default 'Other',
  browser text not null default 'Other',
  utm_source text,
  utm_medium text,
  utm_campaign text
);

create index if not exists hotel_click_events_created_at_idx
  on public.hotel_click_events (created_at desc);

create index if not exists hotel_click_events_event_type_created_at_idx
  on public.hotel_click_events (event_type, created_at desc);

create index if not exists hotel_click_events_page_path_created_at_idx
  on public.hotel_click_events (page_path, created_at desc);

create index if not exists hotel_click_events_visitor_id_idx
  on public.hotel_click_events (visitor_id);

create index if not exists hotel_click_events_session_id_idx
  on public.hotel_click_events (session_id);

alter table public.hotel_click_events enable row level security;

revoke all on table public.hotel_click_events from anon, authenticated;

comment on table public.hotel_click_events is
  'Server-only Supraja Hotels visitor and click events. Raw IP addresses are not stored.';
