"use client";

import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { Building2, KeyRound, RefreshCw, ShieldCheck, UserPlus, Users } from "lucide-react";

type Session={role:"master"|"hotel_admin"};
type Hotel={id:string;name:string;code?:string};
type User={id:string;username:string;display_name:string;hotel_id:string;is_active:boolean;hotels?:{name?:string}|null};
type Employee={id:string;name:string;designation:string;is_active:boolean};
const card="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm";
const input="w-full rounded-xl border border-slate-300 bg-white px-3 py-2.5 text-sm text-slate-900 outline-none focus:border-blue-700 focus:ring-2 focus:ring-blue-100";
const btn="inline-flex items-center justify-center gap-2 rounded-xl px-4 py-2.5 text-sm font-semibold transition disabled:opacity-50";

export default function AccessPage(){
  const[session,setSession]=useState<Session|null>(null),[hotels,setHotels]=useState<Hotel[]>([]),[users,setUsers]=useState<User[]>([]),[employees,setEmployees]=useState<Employee[]>([]),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
  const[loginForm,setLoginForm]=useState({username:"",password:"",hotelId:""});
  const[employeeForm,setEmployeeForm]=useState({name:"",designation:"Manager / Receptionist",pin:""});
  const[resetPassword,setResetPassword]=useState<{id:string;password:string}|null>(null),[resetPin,setResetPin]=useState<{id:string;pin:string}|null>(null);
  const activeUsers=useMemo(()=>users.filter(x=>x.is_active).length,[users]);

  const load=useCallback(async()=>{setMessage("");const sr=await fetch("/api/admin/session",{cache:"no-store"});if(sr.status===401){location.href="/admin/login";return}const sd=await sr.json();if(sd.session.role!=="master"){location.href="/admin/home";return}setSession(sd.session);const[hr,ur,er]=await Promise.all([fetch("/api/admin/hotels",{cache:"no-store"}),fetch("/api/admin/hotel-users",{cache:"no-store"}),fetch("/api/admin/employees",{cache:"no-store"})]);const hd=await hr.json(),ud=await ur.json(),ed=await er.json();const hs=hd.hotels??[];setHotels(hs);setUsers(ud.users??[]);setEmployees(ed.employees??[]);setLoginForm(v=>({...v,hotelId:v.hotelId||hs[0]?.id||""}));if(!ur.ok||!er.ok)setMessage(ud.error||ed.error||"Unable to load access settings.");},[]);
  useEffect(()=>{void load()},[load]);

  async function createLogin(e:FormEvent){e.preventDefault();setBusy(true);const r=await fetch("/api/admin/hotel-users",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(loginForm)}),d=await r.json();setMessage(r.ok?"Hotel login created.":d.error||"Unable to create login.");if(r.ok){setLoginForm(v=>({username:"",password:"",hotelId:v.hotelId}));await load()}setBusy(false)}
  async function createEmployee(e:FormEvent){e.preventDefault();setBusy(true);const r=await fetch("/api/admin/employees",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(employeeForm)}),d=await r.json();setMessage(r.ok?"Employee added.":d.error||"Unable to add employee.");if(r.ok){setEmployeeForm({name:"",designation:"Manager / Receptionist",pin:""});await load()}setBusy(false)}
  async function toggleLogin(u:User){setBusy(true);const r=await fetch("/api/admin/hotel-users",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:u.id,action:"toggle_active",isActive:!u.is_active})});const d=await r.json();setMessage(r.ok?(u.is_active?"Hotel login disabled.":"Hotel login enabled."):d.error);if(r.ok)await load();setBusy(false)}
  async function toggleEmployee(e:Employee){setBusy(true);const r=await fetch("/api/admin/employees",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:e.id,action:"toggle_active",isActive:!e.is_active})});const d=await r.json();setMessage(r.ok?(e.is_active?"Employee disabled.":"Employee enabled."):d.error);if(r.ok)await load();setBusy(false)}
  async function savePassword(e:FormEvent){e.preventDefault();if(!resetPassword)return;setBusy(true);const r=await fetch("/api/admin/hotel-users",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:resetPassword.id,action:"reset_password",password:resetPassword.password})});const d=await r.json();setMessage(r.ok?"Hotel password reset.":d.error);if(r.ok)setResetPassword(null);setBusy(false)}
  async function savePin(e:FormEvent){e.preventDefault();if(!resetPin)return;setBusy(true);const r=await fetch("/api/admin/employees",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:resetPin.id,action:"reset_pin",pin:resetPin.pin})});const d=await r.json();setMessage(r.ok?"Employee PIN reset.":d.error);if(r.ok)setResetPin(null);setBusy(false)}
  if(!session)return <main className="min-h-screen bg-slate-50 p-8">Loading...</main>;

  return <main className="min-h-screen bg-slate-50 text-slate-950"><header className="border-b bg-white"><div className="mx-auto flex max-w-7xl flex-wrap items-center justify-between gap-3 px-4 py-5 sm:px-6"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-amber-600">Supraja Hotels</p><h1 className="text-2xl font-bold">Hotel Access & Employees</h1><p className="mt-1 text-sm text-slate-600">One static login per hotel. Actual employee identity is captured when the shift starts.</p></div><div className="flex gap-2"><Link href="/admin/home" className={`${btn} border bg-white`}>Admin Home</Link><button onClick={()=>void load()} className={`${btn} bg-slate-900 text-white`}><RefreshCw size={16}/>Refresh</button></div></div></header><div className="mx-auto max-w-7xl space-y-5 px-4 py-6 sm:px-6">{message&&<div className="rounded-xl border border-blue-200 bg-blue-50 px-4 py-3 text-sm font-semibold text-blue-900">{message}</div>}

  <section className="grid gap-4 md:grid-cols-3"><div className={card}><Users className="text-blue-800"/><p className="mt-2 text-sm text-slate-500">Hotel logins</p><p className="text-2xl font-bold">{users.length}</p></div><div className={card}><ShieldCheck className="text-emerald-700"/><p className="mt-2 text-sm text-slate-500">Active logins</p><p className="text-2xl font-bold">{activeUsers}</p></div><div className={card}><Building2 className="text-blue-800"/><p className="mt-2 text-sm text-slate-500">Operating hotels</p><p className="text-2xl font-bold">{hotels.length}</p></div></section>

  <section className={card}><h2 className="text-lg font-bold">Create hotel login</h2><p className="mt-1 text-sm text-slate-600">Create only one login for each hotel. Saket Banquet Hall is managed under Hotel Supraja Residency.</p><form onSubmit={createLogin} className="mt-4 grid gap-3 md:grid-cols-4"><select className={input} value={loginForm.hotelId} onChange={e=>setLoginForm(v=>({...v,hotelId:e.target.value}))}>{hotels.map(h=><option key={h.id} value={h.id}>{h.name}</option>)}</select><input className={input} placeholder="Hotel username" value={loginForm.username} onChange={e=>setLoginForm(v=>({...v,username:e.target.value}))} required/><input className={input} type="password" minLength={8} placeholder="Hotel password" value={loginForm.password} onChange={e=>setLoginForm(v=>({...v,password:e.target.value}))} required/><button disabled={busy} className={`${btn} bg-blue-800 text-white`}><UserPlus size={16}/>Create Hotel Login</button></form></section>

  <section className={card}><h2 className="text-lg font-bold">Hotel logins</h2><div className="mt-4 overflow-x-auto"><table className="w-full min-w-[700px] text-left text-sm"><thead><tr className="border-b text-slate-500"><th className="py-3">Hotel</th><th>Username</th><th>Status</th><th>Actions</th></tr></thead><tbody>{users.map(u=><tr key={u.id} className="border-b border-slate-100"><td className="py-3 font-semibold">{u.hotels?.name||u.display_name}</td><td>{u.username}</td><td><span className={`rounded-full px-2 py-1 text-xs font-bold ${u.is_active?"bg-emerald-100 text-emerald-800":"bg-slate-200"}`}>{u.is_active?"Active":"Disabled"}</span></td><td className="space-x-2"><button onClick={()=>void toggleLogin(u)} className="rounded-lg border px-2 py-1 text-xs font-semibold">{u.is_active?"Disable":"Enable"}</button><button onClick={()=>setResetPassword({id:u.id,password:""})} className="rounded-lg border px-2 py-1 text-xs font-semibold">Reset password</button></td></tr>)}{users.length===0&&<tr><td colSpan={4} className="py-8 text-center text-slate-500">No hotel logins created yet.</td></tr>}</tbody></table></div></section>

  <section className={card}><h2 className="text-lg font-bold">Employee master</h2><p className="mt-1 text-sm text-slate-600">Employees are not permanently tied to a hotel. They select their name and enter their personal PIN when starting a shift.</p><form onSubmit={createEmployee} className="mt-4 grid gap-3 md:grid-cols-4"><input className={input} placeholder="Employee name" value={employeeForm.name} onChange={e=>setEmployeeForm(v=>({...v,name:e.target.value}))} required/><input className={input} placeholder="Designation" value={employeeForm.designation} onChange={e=>setEmployeeForm(v=>({...v,designation:e.target.value}))}/><input className={input} inputMode="numeric" pattern="[0-9]{4,6}" placeholder="4-6 digit PIN" value={employeeForm.pin} onChange={e=>setEmployeeForm(v=>({...v,pin:e.target.value.replace(/\D/g,"").slice(0,6)}))} required/><button disabled={busy} className={`${btn} bg-blue-800 text-white`}><UserPlus size={16}/>Add Employee</button></form><div className="mt-4 overflow-x-auto"><table className="w-full min-w-[680px] text-left text-sm"><thead><tr className="border-b text-slate-500"><th className="py-3">Employee</th><th>Designation</th><th>Status</th><th>Actions</th></tr></thead><tbody>{employees.map(e=><tr key={e.id} className="border-b border-slate-100"><td className="py-3 font-semibold">{e.name}</td><td>{e.designation}</td><td>{e.is_active?"Active":"Inactive"}</td><td className="space-x-2"><button onClick={()=>void toggleEmployee(e)} className="rounded-lg border px-2 py-1 text-xs font-semibold">{e.is_active?"Disable":"Enable"}</button><button onClick={()=>setResetPin({id:e.id,pin:""})} className="rounded-lg border px-2 py-1 text-xs font-semibold">Reset PIN</button></td></tr>)}{employees.length===0&&<tr><td colSpan={4} className="py-8 text-center text-slate-500">No employees added yet.</td></tr>}</tbody></table></div></section>

  {resetPassword&&<section className="rounded-2xl border border-amber-200 bg-amber-50 p-5"><h2 className="font-bold">Reset hotel password</h2><form onSubmit={savePassword} className="mt-3 flex max-w-xl gap-2"><input className={input} type="password" minLength={8} placeholder="New password" value={resetPassword.password} onChange={e=>setResetPassword(v=>v?{...v,password:e.target.value}:v)} required/><button className={`${btn} bg-amber-700 text-white`}><KeyRound size={15}/>Save</button><button type="button" onClick={()=>setResetPassword(null)} className={`${btn} border bg-white`}>Cancel</button></form></section>}
  {resetPin&&<section className="rounded-2xl border border-amber-200 bg-amber-50 p-5"><h2 className="font-bold">Reset employee PIN</h2><form onSubmit={savePin} className="mt-3 flex max-w-xl gap-2"><input className={input} inputMode="numeric" pattern="[0-9]{4,6}" placeholder="New 4-6 digit PIN" value={resetPin.pin} onChange={e=>setResetPin(v=>v?{...v,pin:e.target.value.replace(/\D/g,"").slice(0,6)}:v)} required/><button className={`${btn} bg-amber-700 text-white`}>Save PIN</button><button type="button" onClick={()=>setResetPin(null)} className={`${btn} border bg-white`}>Cancel</button></form></section>}
  </div></main>;
}
