import type { Metadata } from "next";
import Link from "next/link";
import { CalendarDays, CheckCircle2, MapPin, MessageCircle, Phone, Sparkles } from "lucide-react";
import SmartImage from "@/components/SmartImage";

const siteUrl="https://www.suprajahotels.com";
const phone="9346316161";
const latitude=17.494703099705735;
const longitude=78.32400007462928;
const mapsUrl=`https://www.google.com/maps/search/?api=1&query=${latitude},${longitude}`;
const pageUrl=`${siteUrl}/saket-banquet-hall`;
const whatsappUrl="https://wa.me/919346316161?text=Hi%20I%20would%20like%20to%20check%20availability%20for%20Saket%20Banquet%20Hall%20at%20Hotel%20Supraja%20Residency";

export const metadata: Metadata={title:"Saket Banquet Hall in Chandanagar",description:"Saket Banquet Hall at Hotel Supraja Residency in Chandanagar for family functions, celebrations, meetings and private events. Call or WhatsApp for availability.",alternates:{canonical:pageUrl},openGraph:{title:"Saket Banquet Hall in Chandanagar | Supraja Hotels",description:"View Saket Banquet Hall at Hotel Supraja Residency and contact the team directly for current date availability.",url:pageUrl,siteName:"Supraja Hotels",images:[{url:"/images/social/saket-banquet-hall-og.jpg",width:1200,height:630,alt:"Saket Banquet Hall in Chandanagar"}],locale:"en_IN",type:"website"}};

const gallery=["banquet-hall-seating","banquet-hall-overview","banquet-hall-stage","banquet-hall-main","banquet-hall-conference","banquet-hall-lobby","banquet-hall-overview-2","banquet-hall-event-stage"];
const social=["Engagements","Birthday Celebrations","Anniversary Functions","Naming Ceremonies","Family Gatherings"];
const professional=["Corporate Meetings","Training Sessions","Private Gatherings"];

export default function SaketBanquetHallPage(){
 const schema={"@context":"https://schema.org","@type":"EventVenue","@id":`${pageUrl}#venue`,name:"Saket Banquet Hall",url:pageUrl,telephone:`+91-${phone}`,address:{"@type":"PostalAddress",streetAddress:"Plot No. 4-91, Above Parampara Sweets",addressLocality:"Chandanagar",addressRegion:"Telangana",postalCode:"500050",addressCountry:"IN"},geo:{"@type":"GeoCoordinates",latitude,longitude},hasMap:mapsUrl,containedInPlace:{"@id":`${siteUrl}/hotels/supraja-residency#hotel`},parentOrganization:{"@id":`${siteUrl}/#organization`}};
 return <main className="bg-white pb-20 text-slate-900 md:pb-0"><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema)}}/>
  <section className="relative isolate flex min-h-[650px] items-end overflow-hidden bg-slate-950 text-white md:items-center"><SmartImage src="/images/banquet-hall/banquet-hall-seating.webp" alt="Saket Banquet Hall in Chandanagar" fill isHero className="object-cover" sizes="100vw"/><video autoPlay muted loop playsInline preload="metadata" poster="/images/banquet-hall/banquet-hall-seating.webp" aria-hidden="true" className="absolute inset-0 h-full w-full object-cover"><source src="/images/hero-vids/saket-banquet-hall-hero-video.webm" type="video/webm"/></video><div className="absolute inset-0 bg-gradient-to-r from-slate-950/92 via-slate-950/52 to-transparent"/><div className="absolute inset-0 bg-gradient-to-t from-slate-950/85 via-transparent to-slate-950/10"/><div className="container-custom relative z-10 w-full px-5 pb-12 pt-32 md:py-20"><div className="max-w-4xl"><p className="text-sm font-bold uppercase tracking-[0.24em] text-amber-300">Saket Banquet Hall · Chandanagar</p><h1 className="mt-4 text-4xl font-bold leading-[1.05] tracking-tight md:text-6xl">A Flexible Event Venue Inside Hotel Supraja Residency</h1><p className="mt-6 max-w-3xl text-lg leading-8 text-slate-200">Plan family celebrations, meetings and private gatherings at the second-floor Saket Banquet Hall in Chandanagar. Contact the property team directly to check date availability and event requirements.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><a href={whatsappUrl} target="_blank" rel="noopener noreferrer" className="inline-flex min-h-12 items-center justify-center gap-2 rounded-full bg-green-600 px-7 text-sm font-bold"><MessageCircle size={18}/>Check Date Availability</a><a href={`tel:+91${phone}`} className="inline-flex min-h-12 items-center justify-center gap-2 rounded-full bg-white px-7 text-sm font-bold text-slate-950"><Phone size={18}/>Call {phone}</a></div></div></div></section>

  <section className="bg-[#f7f5f1] px-4 py-16 lg:py-24"><div className="container-custom"><div className="max-w-5xl"><p className="text-sm font-bold uppercase tracking-[0.22em] text-amber-700">Venue Gallery</p><h2 className="mt-3 text-3xl font-bold tracking-tight md:text-5xl">See the Hall Before You Plan Your Event</h2><p className="mt-5 max-w-3xl leading-8 text-slate-600">Review the seating, stage and open event areas before contacting the property.</p></div><div className="mt-10 grid gap-3 md:grid-cols-4">{gallery.map((name,i)=><div key={name} className={`relative overflow-hidden rounded-[1.5rem] ${i===0?'md:col-span-2 md:row-span-2 min-h-[380px]':'min-h-[220px]'}`}><SmartImage src={`/images/banquet-hall/${name}.webp`} alt={`Saket Banquet Hall view ${i+1}`} fill className="object-cover transition duration-700 hover:scale-105" sizes="(max-width:768px) 100vw,25vw"/></div>)}</div></div></section>

  <section className="bg-white px-4 py-16 lg:py-24"><div className="container-custom"><div className="text-center"><p className="text-sm font-bold uppercase tracking-[0.22em] text-amber-700">Event Types</p><h2 className="mt-3 text-3xl font-bold tracking-tight md:text-4xl lg:text-5xl xl:whitespace-nowrap">Suitable for Social and Professional Gatherings</h2></div><div className="mx-auto mt-10 grid max-w-5xl gap-6 md:grid-cols-2"><div className="rounded-[1.75rem] bg-[#f7f5f1] p-7"><h3 className="text-2xl font-bold">Social Celebrations</h3><div className="mt-6 grid gap-4">{social.map(x=><p key={x} className="flex items-center gap-3 font-semibold text-slate-700"><Sparkles size={18} className="text-amber-700"/>{x}</p>)}</div></div><div className="rounded-[1.75rem] bg-slate-950 p-7 text-white"><h3 className="text-2xl font-bold">Professional Events</h3><div className="mt-6 grid gap-4">{professional.map(x=><p key={x} className="flex items-center gap-3 font-semibold text-slate-200"><CalendarDays size={18} className="text-amber-300"/>{x}</p>)}</div></div></div></div></section>

  <section className="bg-[#f7f5f1] px-4 py-16 lg:py-20"><div className="container-custom grid gap-8 lg:grid-cols-2"><div><p className="text-sm font-bold uppercase tracking-[0.22em] text-amber-700">Event + Stay</p><h2 className="mt-3 text-3xl font-bold tracking-tight md:text-4xl">Hotel Rooms in the Same Property</h2><p className="mt-5 leading-8 text-slate-600">Guests attending an event can also enquire about rooms at Hotel Supraja Residency. Room booking is separate from the banquet hall and depends on current availability.</p><Link href="/hotels/supraja-residency" className="mt-6 inline-block text-sm font-bold text-blue-800 hover:underline">View Hotel Supraja Residency</Link></div><div className="rounded-[1.75rem] bg-white p-7 shadow-sm"><p className="text-sm font-bold uppercase tracking-[0.2em] text-amber-700">Location</p><h3 className="mt-3 text-2xl font-bold">Inside Hotel Supraja Residency</h3><p className="mt-4 flex gap-3 leading-7 text-slate-600"><MapPin size={20} className="mt-1 shrink-0 text-blue-700"/>Plot No. 4-91, Above Parampara Sweets, Chandanagar, Hyderabad, Telangana 500050.</p><div className="mt-6 space-y-3">{["Second-floor event space","Direct date availability enquiry","Hotel rooms available separately","Suitable for social and professional events"].map(x=><p key={x} className="flex gap-3 text-slate-700"><CheckCircle2 size={18} className="mt-1 text-green-700"/>{x}</p>)}</div></div></div></section>

  <section className="bg-slate-950 px-4 py-16 text-white"><div className="container-custom flex flex-col justify-between gap-6 md:flex-row md:items-center"><div><p className="text-sm font-bold uppercase tracking-[0.2em] text-amber-300">Plan Your Event</p><h2 className="mt-2 text-3xl font-bold">Check Saket Banquet Hall Availability</h2></div><div className="flex gap-3"><a href={`tel:+91${phone}`} className="inline-flex min-h-12 items-center gap-2 rounded-full bg-white px-6 text-sm font-bold text-slate-950"><Phone size={17}/>Call</a><a href={whatsappUrl} target="_blank" rel="noopener noreferrer" className="inline-flex min-h-12 items-center gap-2 rounded-full bg-green-600 px-6 text-sm font-bold"><MessageCircle size={17}/>WhatsApp</a></div></div></section>

  <div className="fixed inset-x-0 bottom-0 z-50 grid grid-cols-2 border-t border-slate-200 bg-white p-2 shadow-[0_-8px_30px_rgba(15,23,42,.14)] md:hidden"><a href={`tel:+91${phone}`} className="inline-flex min-h-12 items-center justify-center gap-2 text-sm font-bold"><Phone size={18}/>Call</a><a href={whatsappUrl} target="_blank" rel="noopener noreferrer" className="inline-flex min-h-12 items-center justify-center gap-2 rounded-full bg-green-600 text-sm font-bold text-white"><MessageCircle size={18}/>Check Date</a></div>
 </main>;
}
