"use client";

import {useEffect,useMemo,useState} from "react";
import {Download} from "lucide-react";

type Hotel={id:string;name:string};
type Session={role:"master"|"hotel_admin"};
function indiaDate(offset=0){const d=new Date(Date.now()+offset*86400000);return new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Kolkata",year:"numeric",month:"2-digit",day:"2-digit"}).format(d)}

export default function AttendanceExportPage(){
 const[session,setSession]=useState<Session|null>(null),[hotels,setHotels]=useState<Hotel[]>([]),[hotelId,setHotelId]=useState(""),[from,setFrom]=useState(indiaDate(-30)),[to,setTo]=useState(indiaDate()),[error,setError]=useState("");
 useEffect(()=>{void(async()=>{const[sr,hr]=await Promise.all([fetch("/api/admin/session",{cache:"no-store"}),fetch("/api/admin/hotels",{cache:"no-store"})]);if(sr.status===401){location.href="/admin/login";return}const sd=await sr.json();if(sd.session.role!=="master"){location.href="/admin/home";return}setSession(sd.session);if(hr.ok){const hd=await hr.json();setHotels(hd.hotels??[])}else setError("Unable to load hotels.")})()},[]);
 const exportUrl=useMemo(()=>{const q=new URLSearchParams({from,to,format:"csv"});if(hotelId)q.set("hotelId",hotelId);return `/api/admin/attendance-history?${q}`},[from,to,hotelId]);
 if(!session)return <main className="min-h-screen bg-slate-50 p-8 text-slate-600">Loading export...</main>;
 return <main className="min-h-screen bg-slate-50 text-slate-950"><header className="border-b bg-white"><div className="mx-auto max-w-5xl px-4 py-6 sm:px-6"><p className="text-xs font-bold uppercase tracking-[.18em] text-amber-600">Supraja Hotels</p><h1 className="mt-1 text-2xl font-bold">Attendance Export</h1><p className="mt-1 text-sm text-slate-600">Download cleaning staff attendance for payroll and management records.</p></div></header><div className="mx-auto max-w-5xl px-4 py-6 sm:px-6">{error&&<div className="mb-4 rounded-xl border border-red-200 bg-red-50 p-3 text-sm font-semibold text-red-800">{error}</div>}<section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="grid gap-4 md:grid-cols-3"><label className="text-sm font-semibold text-slate-700">From<input type="date" value={from} max={to} onChange={e=>setFrom(e.target.value)} className="mt-2 w-full rounded-xl border border-slate-300 px-3 py-2.5 text-sm"/></label><label className="text-sm font-semibold text-slate-700">To<input type="date" value={to} min={from} onChange={e=>setTo(e.target.value)} className="mt-2 w-full rounded-xl border border-slate-300 px-3 py-2.5 text-sm"/></label><label className="text-sm font-semibold text-slate-700">Hotel<select value={hotelId} onChange={e=>setHotelId(e.target.value)} className="mt-2 w-full rounded-xl border border-slate-300 bg-white px-3 py-2.5 text-sm"><option value="">All hotels</option>{hotels.map(h=><option key={h.id} value={h.id}>{h.name}</option>)}</select></label></div><div className="mt-5 flex flex-wrap items-center justify-between gap-3 border-t border-slate-100 pt-5"><p className="text-sm text-slate-600">Exports the selected period with date, hotel, staff name, staff type, attendance status, exact marked time and recorded-by employee.</p><a href={exportUrl} className="inline-flex items-center gap-2 rounded-xl bg-blue-800 px-4 py-2.5 text-sm font-semibold text-white hover:bg-blue-900"><Download size={16}/>Download CSV</a></div></section></div></main>;
}
