"use client";

import { useEffect, useState } from "react";
import { AlertTriangle, CheckCircle2, Clock3, UserCheck } from "lucide-react";

type Session={displayName:string;role:"master"|"hotel_admin";hotelName:string|null};
type Summary={id:string;name:string;code:string;onDuty:{employeeName:string;startedAt:string;shiftId:string;shiftType?:string|null;isLate?:boolean;lateMinutes?:number;lateReason?:string|null}|null;cleaningStaff:{total:number;marked:number};checklists:{shiftStart:{done:number;total:number};daily:{done:number;total:number};shiftEnd:{done:number;total:number}};issues:{complaints:number;maintenance:number;critical:number}};

export default function AdminHome(){
 const[s,setS]=useState<Session|null>(null),[summaries,setSummaries]=useState<Summary[]>([]),[date,setDate]=useState(""),[error,setError]=useState("");
 useEffect(()=>{void(async()=>{const [sr,rr]=await Promise.all([fetch("/api/admin/session",{cache:"no-store"}),fetch("/api/admin/home-summary",{cache:"no-store"})]);if(sr.status===401){location.href="/admin/login";return}const sd=await sr.json();setS(sd.session);const rd=await rr.json();if(rr.ok){setSummaries(rd.hotels??[]);setDate(rd.date??"")}else setError(rd.error??"Unable to load today's summary.")})()},[]);
 if(!s)return <main className="min-h-screen bg-slate-50 p-8 text-slate-600">Loading today&apos;s operations...</main>;
 const identity=s.role==="master"?"All operating hotels":s.hotelName||s.displayName;
 const dateLabel=date?new Date(`${date}T00:00:00`).toLocaleDateString("en-IN",{weekday:"long",day:"numeric",month:"long",year:"numeric"}):"Today";
 return <main className="min-h-screen bg-slate-50 text-slate-950"><header className="border-b bg-white"><div className="mx-auto max-w-7xl px-4 py-6 sm:px-6"><p className="text-xs font-bold uppercase tracking-[.18em] text-amber-600">Supraja Hotels</p><h1 className="mt-1 text-2xl font-bold">Today&apos;s Operations</h1><p className="mt-1 text-sm text-slate-600">{identity} · {dateLabel}</p></div></header><div className="mx-auto max-w-7xl px-4 py-6 sm:px-6">{error&&<div className="mb-4 rounded-xl border border-red-200 bg-red-50 p-3 text-sm font-semibold text-red-800">{error}</div>}<div className={`grid gap-4 ${s.role==="master"?"lg:grid-cols-3":"max-w-4xl"}`}>{summaries.map(h=><HotelDayCard key={h.id} hotel={h}/>)}</div>{!error&&summaries.length===0&&<div className="rounded-2xl border border-slate-200 bg-white p-8 text-center text-sm text-slate-600">No operating-hotel summary is available.</div>}</div></main>
}

function HotelDayCard({hotel:h}:{hotel:Summary}){
 const attendanceComplete=h.cleaningStaff.total>0&&h.cleaningStaff.marked>=h.cleaningStaff.total,issueCount=h.issues.complaints+h.issues.maintenance;
 return <section className={`overflow-hidden rounded-2xl border bg-white shadow-sm ${h.onDuty?.isLate?"border-red-300":"border-slate-200"}`}>
  <div className="border-b border-slate-100 p-5"><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-wide text-slate-500">{h.name}</p><div className="mt-3 flex items-center gap-3"><div className={`flex h-10 w-10 items-center justify-center rounded-full ${h.onDuty?.isLate?"bg-red-50 text-red-700":h.onDuty?"bg-emerald-50 text-emerald-700":"bg-amber-50 text-amber-700"}`}><Clock3 size={19}/></div><div><p className="text-xs text-slate-500">On duty</p><p className="text-lg font-bold">{h.onDuty?.employeeName??"No active shift"}</p>{h.onDuty&&<p className="text-xs text-slate-500">{h.onDuty.shiftType?`${h.onDuty.shiftType[0].toUpperCase()+h.onDuty.shiftType.slice(1)} · `:""}Since {new Date(h.onDuty.startedAt).toLocaleTimeString("en-IN",{hour:"numeric",minute:"2-digit"})}</p>}</div></div>{h.onDuty?.isLate&&<div className="mt-3 rounded-lg border border-red-200 bg-red-50 p-2.5 text-xs text-red-800"><b>Late start: {h.onDuty.lateMinutes} min</b>{h.onDuty.lateReason&&<p className="mt-1">{h.onDuty.lateReason}</p>}</div>}</div><div className="flex flex-col items-end gap-2">{h.onDuty?.isLate&&<span className="rounded-full bg-red-100 px-2.5 py-1 text-xs font-bold text-red-800">Late</span>}{h.issues.critical>0&&<span className="rounded-full bg-red-100 px-2.5 py-1 text-xs font-bold text-red-800">{h.issues.critical} critical</span>}</div></div></div>
  <div className="grid grid-cols-2 gap-px bg-slate-200"><div className="bg-white p-4"><div className="flex items-center gap-2 text-xs font-medium text-slate-500"><UserCheck size={15}/>Cleaning staff</div><p className="mt-1 text-lg font-bold">{h.cleaningStaff.marked}/{h.cleaningStaff.total}</p><p className={`text-xs ${attendanceComplete?"text-emerald-700":"text-slate-500"}`}>{attendanceComplete?"Attendance complete":"Attendance marked"}</p></div><div className="bg-white p-4"><div className="flex items-center gap-2 text-xs font-medium text-slate-500"><AlertTriangle size={15}/>Open issues</div><p className="mt-1 text-lg font-bold">{issueCount}</p><p className="text-xs text-slate-500">{h.issues.complaints} complaints · {h.issues.maintenance} maintenance</p></div></div>
  <div className="space-y-3 p-5"><ChecklistRow label="Shift Start" done={h.checklists.shiftStart.done} total={h.checklists.shiftStart.total}/><ChecklistRow label="Daily Checklist" done={h.checklists.daily.done} total={h.checklists.daily.total}/><ChecklistRow label="Shift End" done={h.checklists.shiftEnd.done} total={h.checklists.shiftEnd.total}/></div>
 </section>
}
function ChecklistRow({label,done,total}:{label:string;done:number;total:number}){const complete=done>=total&&total>0,pct=total?Math.min(100,Math.round(done/total*100)):0;return <div><div className="mb-1.5 flex items-center justify-between gap-3 text-sm"><span className="flex items-center gap-1.5 font-medium text-slate-700">{complete&&<CheckCircle2 size={15} className="text-emerald-700"/>}{label}</span><span className={complete?"font-bold text-emerald-700":"font-bold text-slate-700"}>{done}/{total}</span></div><div className="h-2 overflow-hidden rounded-full bg-slate-100"><div className={`h-full rounded-full ${complete?"bg-emerald-600":"bg-blue-700"}`} style={{width:`${pct}%`}}/></div></div>}
