"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { ArrowRight, BedDouble, ClipboardCheck, DoorOpen, ListChecks, ShieldAlert, Users, Wrench, Clock3, UserCheck, AlertTriangle } from "lucide-react";

type Session={displayName:string;role:"master"|"hotel_admin";hotelName:string|null};
type Summary={id:string;name:string;code:string;onDuty:{employeeName:string;startedAt:string;shiftId:string}|null;cleaningStaff:{total:number;marked:number};checklists:{shiftStart:{done:number;total:number};daily:{done:number;total:number};shiftEnd:{done:number;total:number}};issues:{complaints:number;maintenance:number;critical:number}};
const tiles=[{href:"/admin/checklists",title:"Checklists",desc:"Shift start, daily and shift end controls",icon:ListChecks},{href:"/admin/operations",title:"Attendance & Shift",desc:"Employee shift and timestamped cleaning staff attendance",icon:Users},{href:"/admin/rooms",title:"Rooms",desc:"Live room board and room status",icon:BedDouble},{href:"/admin/controls",title:"Daily Controls",desc:"Cash closing, complaints and maintenance",icon:ClipboardCheck},{href:"/admin/housekeeping",title:"Housekeeping",desc:"Dirty rooms, cleaning and ready status",icon:DoorOpen},{href:"/admin/handovers",title:"Shift Handover",desc:"Outgoing and incoming responsibility",icon:Wrench},{href:"/admin/exceptions",title:"Exceptions",desc:"Warnings that need management attention",icon:ShieldAlert}];
const card="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm";

export default function AdminHome(){
 const[s,setS]=useState<Session|null>(null),[summaries,setSummaries]=useState<Summary[]>([]),[date,setDate]=useState(""),[error,setError]=useState("");
 useEffect(()=>{void(async()=>{const [sr,rr]=await Promise.all([fetch("/api/admin/session",{cache:"no-store"}),fetch("/api/admin/home-summary",{cache:"no-store"})]);if(sr.status===401){location.href="/admin/login";return}const sd=await sr.json();setS(sd.session);const rd=await rr.json();if(rr.ok){setSummaries(rd.hotels??[]);setDate(rd.date??"")}else setError(rd.error??"Unable to load today's summary.")})()},[]);
 if(!s)return <main className="min-h-screen bg-slate-50 p-8 text-slate-600">Loading...</main>;
 const all=s.role==="master"?[...tiles,{href:"/admin/users",title:"Access & Employees",desc:"One login per hotel and employee PIN master",icon:Users}]:tiles;
 const identity=s.role==="master"?"Master Admin":s.hotelName||s.displayName;
 const dateLabel=date?new Date(`${date}T00:00:00`).toLocaleDateString("en-IN",{weekday:"long",day:"numeric",month:"long",year:"numeric"}):"Today";
 return <main className="min-h-screen bg-slate-50 text-slate-950">
  <header className="border-b bg-white"><div className="mx-auto max-w-7xl px-4 py-6 sm:px-6"><p className="text-xs font-bold uppercase tracking-[.18em] text-amber-600">Supraja Hotels</p><div className="mt-1"><h1 className="text-2xl font-bold">Hotel Operations</h1><p className="mt-1 text-sm text-slate-600">{identity} · {dateLabel}</p></div></div></header>
  <div className="mx-auto max-w-7xl space-y-6 px-4 py-6 sm:px-6">
   {error&&<div className="rounded-xl border border-red-200 bg-red-50 p-3 text-sm font-semibold text-red-800">{error}</div>}
   <section><div className="mb-3"><h2 className="text-lg font-bold">Today at a glance</h2><p className="text-sm text-slate-600">Who is on duty, attendance progress, checklist status and open issues.</p></div><div className={`grid gap-4 ${s.role==="master"?"lg:grid-cols-3":"max-w-4xl"}`}>{summaries.map(h=><div key={h.id} className={card}><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-wide text-slate-500">{h.name}</p><div className="mt-2 flex items-center gap-2"><Clock3 size={18} className={h.onDuty?"text-emerald-700":"text-amber-700"}/><div><p className="text-xs text-slate-500">On duty</p><p className="font-bold">{h.onDuty?.employeeName??"No active shift"}</p></div></div>{h.onDuty&&<p className="mt-1 text-xs text-slate-500">Started {new Date(h.onDuty.startedAt).toLocaleString("en-IN")}</p>}</div>{h.issues.critical>0&&<span className="rounded-full bg-red-100 px-2 py-1 text-xs font-bold text-red-800">{h.issues.critical} critical</span>}</div><div className="mt-4 grid grid-cols-2 gap-2 text-sm"><div className="rounded-xl bg-slate-50 p-3"><div className="flex items-center gap-1.5 text-slate-500"><UserCheck size={14}/>Staff attendance</div><p className="mt-1 font-bold">{h.cleaningStaff.marked}/{h.cleaningStaff.total} marked</p></div><div className="rounded-xl bg-slate-50 p-3"><div className="flex items-center gap-1.5 text-slate-500"><AlertTriangle size={14}/>Open issues</div><p className="mt-1 font-bold">{h.issues.complaints+h.issues.maintenance}</p><p className="text-[11px] text-slate-500">{h.issues.complaints} complaints · {h.issues.maintenance} maintenance</p></div></div><div className="mt-3 space-y-2 text-xs"><Progress label="Shift Start" done={h.checklists.shiftStart.done} total={h.checklists.shiftStart.total}/><Progress label="Daily" done={h.checklists.daily.done} total={h.checklists.daily.total}/><Progress label="Shift End" done={h.checklists.shiftEnd.done} total={h.checklists.shiftEnd.total}/></div></div>)}</div></section>
   <section><h2 className="mb-3 text-lg font-bold">Operations</h2><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{all.map(t=>{const Icon=t.icon;return <Link key={t.href} href={t.href} className="group rounded-2xl border border-slate-200 bg-white p-5 shadow-sm transition hover:-translate-y-0.5 hover:shadow-md"><div className="flex items-start justify-between gap-4"><div className="flex h-11 w-11 items-center justify-center rounded-xl bg-blue-50 text-blue-800"><Icon size={21}/></div><ArrowRight size={18} className="text-slate-400 transition group-hover:translate-x-1"/></div><h2 className="mt-4 text-lg font-bold">{t.title}</h2><p className="mt-1 text-sm leading-6 text-slate-600">{t.desc}</p></Link>})}</div></section>
  </div>
 </main>
}

function Progress({label,done,total}:{label:string;done:number;total:number}){const pct=Math.min(100,Math.round(done/total*100));return <div><div className="mb-1 flex justify-between"><span className="text-slate-600">{label}</span><b>{done}/{total}</b></div><div className="h-1.5 overflow-hidden rounded-full bg-slate-200"><div className="h-full rounded-full bg-blue-800" style={{width:`${pct}%`}}/></div></div>}
